baseurl = "https://www.comicsncoffee.com/"
title = "Comics 'N' Coffee"
languageCode = "en-us"
theme = "cnc-2018"

googleAnalytics = "UA-115297583-3"
disqusShortname = "comicsncoffee"

enableEmoji = true
enableRobotsTXT = true

[params]
	author = "Ricardo N Feliciano & Moises Lopez"
	profilepic = "/assets/img/logo-icon-no-bg.svg"
	description = "Independent community of Marvel and DC fans. Covering the movies, TV shows, figures, and of course, the comics. For fans, by fans."
	githubUsername = "felicianotech"
	accent = "#FFFFFF"
	backgroundColor = "#18191C"
	font = "Raleway"
	hightlight = true
	highlightStyle = "solarized-dark"
	highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[blackfriday]
	hrefTargetBlank	=	true

[social]
	twitter = "Comics_NCoffee"


[[menu.main]]
	name	= "Home"
	url		= "/"
	weight	= -1

[[menu.main]]
	name	= "Social Network"
	url		= "/social/"
	weight	= 4

[[menu.main]]
	name	= "Podcast"
	url		= "/podcast/"
	weight	= 5

[[menu.main]]
	name	= "Events"
	url		= "/events/"
	weight	= 10

[[menu.main]]
	name	= "Newsletter"
	url		= "/newsletter/"
	weight	= 15

[[menu.main]]
	name	= "Contact Us"
	url		= "/contact/"
	weight	= 20

[[menu.main]]
	name	= "About"
	url		= "/about/"
	weight	= 25


[[menu.social]]
    url = "https://twitter.com/Comics_NCoffee/"
    name = "twitter"
    weight = 1

[[menu.social]]
    url = "https://www.facebook.com/ComicsNCoffee/"
    name = "facebook"
    weight = 2

[[menu.social]]
    name = "instagram"
    url = "https://www.instagram.com/comicsncoffee/"
    weight = 3

[[menu.social]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCNCoJDuMl4r4Q0SjNgYS2kA"
    weight = 4

[[menu.social]]
    name = "google-plus"
    url = "https://plus.google.com/113015979305406231545"
    weight = 5

[[menu.social]]
    name = "github"
    url = "https://github.com/comicsncoffee/www.comicsncoffee.com"
    weight = 6
